# Quadratic function configuration
_target_: optHIM.functions.quadratic.Quadratic

# Function parameters
data_file: ${hydra:runtime.cwd}/data/quadratic/P1_quad_10_10.npy

# Initial point generated in code