# Quadratic function configuration
_target_: optHIM.functions.quadratic.Quadratic

# Function parameters
data_file: ${hydra:runtime.cwd}/data/quadratic/P3_quad_1000_10.npy

# Initial point generated in code