# Quadratic function configuration
_target_: optHIM.functions.quadratic.Quadratic

# Function parameters
data_file: ${hydra:runtime.cwd}/data/quadratic/P4_quad_1000_1000.npy

# Initial point generated in code