# Gradient Descent configuration
_target_: optim.algorithms.gd.GD

# Algorithm parameters
step_type: constant  # Options: constant, armijo
step_size: 1e-3      # Used for constant step type
alpha: 1.0           # Initial step size for armijo step type
tau: 0.5             # Step size reduction factor for armijo
c1: 1e-4             # Sufficient decrease parameter for armijo 