# Gradient Descent configuration
_target_: optHIM.algorithms.gd.GD

# Algorithm parameters
step_type:   armijo    # Type of step size: constant, diminish, armijo, or wolfe
step_size:   1e-3      # Step size for constant step type
alpha:       1.0       # Initial step size for armijo/wolfe line search
tau:         0.5       # Step size reduction factor for armijo
c1:          1e-4      # Sufficient decrease parameter for armijo/wolfe
c2:          0.9       # Curvature condition parameter for wolfe
alpha_high:  1000.0    # Upper bound for step size in wolfe
alpha_low:   0.0       # Lower bound for step size in wolfe
c:           0.5       # Interpolation parameter for wolfe