# Newton's Method configuration
_target_: optHIM.algorithms.newton.Newton

# Algorithm parameters
beta: 1e-6           # Positive scalar for Hessian modification
step_type: armijo    # Options: constant, armijo
step_size: 1.0       # Used for constant step type
alpha: 1.0           # Initial step size for armijo step type
tau: 0.5             # Step size reduction factor for armijo
c1: 1e-4             # Sufficient decrease parameter for armijo