# @package _global_

defaults:
  - algorithm: gd
  - function: quadratic
  - optimizer: default
  - _self_

# Experiment settings
experiment:
  name: default_exp
  seed: 42
  max_iter: 100
  
# Logging settings
logging:
  level: INFO
  save_dir: ./logs 