# @package _global_

defaults:
  - algorithm: gd
  - function: quadratic
  - _self_

# Experiment settings
experiment:
  name: default_exp
  seed: 42
  max_iter: 100
  tol: 1e-6
  
# Logging settings
logging:
  level: INFO
  log_dir: ./logs 
  save_traj: True
  plot_traj: True
  plot_loss: Trues