# @package _global_

defaults:
  - algorithm: gd
  - function: quadratic
  - _self_

hydra:
  run:
    dir: ${experiment.name}
  sweep:
    dir: ${experiment.name}
    subdir: ""

# Experiment settings
experiment:
  name: outputs/default
  seed: 42
  batch_size: 1
  max_iter: 1000
  tol: 1e-6
  
# Logging settings
logging:
  level: INFO
  save_traj: True
  save_loss: True
  save_grad_norm: True
  plot_traj: True
  plot_loss: True
  plot_grad_norm: True